project:
  type: website

website:
  title: "Gabriel Ortiz"
  favicon: bird.svg
  navbar:
    pinned: true
    search: true
    right:
      - text: "Home"
        href: index.md
      - text: "Riscos"
        href: riscos.md
      - text: "Economia"
        href: economia.md
        
format:
  html:
    theme: flatly
    toc: true
